INSERT INTO ESTADO (id,sigla) VALUES (1,'AC');
INSERT INTO ESTADO (id,sigla) VALUES (2,'AL');
INSERT INTO ESTADO (id,sigla) VALUES (3,'AM');
INSERT INTO ESTADO (id,sigla) VALUES (4,'AP');
INSERT INTO ESTADO (id,sigla) VALUES (5,'BA');
INSERT INTO ESTADO (id,sigla) VALUES (6,'CE');
INSERT INTO ESTADO (id,sigla) VALUES (7,'DF');
INSERT INTO ESTADO (id,sigla) VALUES (8,'ES');
INSERT INTO ESTADO (id,sigla) VALUES (9,'GO');
INSERT INTO ESTADO (id,sigla) VALUES (10,'MA');
INSERT INTO ESTADO (id,sigla) VALUES (11,'MG');
INSERT INTO ESTADO (id,sigla) VALUES (12,'MS');
INSERT INTO ESTADO (id,sigla) VALUES (13,'MT');
INSERT INTO ESTADO (id,sigla) VALUES (14,'PA');
INSERT INTO ESTADO (id,sigla) VALUES (15,'PB');
INSERT INTO ESTADO (id,sigla) VALUES (16,'PE');
INSERT INTO ESTADO (id,sigla) VALUES (17,'PI');
INSERT INTO ESTADO (id,sigla) VALUES (18,'PR');
INSERT INTO ESTADO (id,sigla) VALUES (19,'RJ');
INSERT INTO ESTADO (id,sigla) VALUES (20,'RN');
INSERT INTO ESTADO (id,sigla) VALUES (21,'RO');
INSERT INTO ESTADO (id,sigla) VALUES (22,'RR');
INSERT INTO ESTADO (id,sigla) VALUES (23,'RS');
INSERT INTO ESTADO (id,sigla) VALUES (24,'SC');
INSERT INTO ESTADO (id,sigla) VALUES (25,'SE');
INSERT INTO ESTADO (id,sigla) VALUES (26,'SP');
INSERT INTO ESTADO (id,sigla) VALUES (27,'TO');

INSERT INTO CIDADE (id, nome, estado_id) VALUES (1, 'Afonso Cláudio', 8);
INSERT INTO CIDADE (id, nome, estado_id) VALUES (2, 'Água Doce do Norte', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (3, 'Águia Branca', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (4, 'Alegre', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (5, 'Alfredo Chaves', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (6, 'Alto Rio Novo', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (7, 'Anchieta', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (8, 'Apiacá', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (9, 'Aracruz', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (10, 'Atilio Vivacqua', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (11, 'Baixo Guandu', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (12, 'Barra de São Francisco', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (13, 'Boa Esperança', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (14, 'Bom Jesus do Norte', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (15, 'Brejetuba', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (16, 'Cachoeiro de Itapemirim', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (17, 'Cariacica', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (18, 'Castelo', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (19, 'Colatina', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (20, 'Conceição da Barra', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (21, 'Conceição do Castelo', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (22, 'Divino de São Lourenço', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (23, 'Domingos Martins', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (24, 'Dores do Rio Preto', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (25, 'Ecoporanga', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (26, 'Fundão', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (27, 'Governador Lindenberg', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (28, 'Guaçuí', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (29, 'Guarapari', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (30, 'Ibatiba', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (31, 'Ibiraçu', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (32, 'Ibitirama', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (33, 'Iconha', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (34, 'Irupi', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (35, 'Itaguaçu', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (36, 'Itapemirim', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (37, 'Itarana', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (38, 'Iúna', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (39, 'Jaguaré', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (40, 'Jerônimo Monteiro', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (41, 'João Neiva', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (42, 'Laranja da Terra', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (43, 'Linhares', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (44, 'Mantenópolis', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (45, 'Marataízes', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (46, 'Marechal Floriano', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (47, 'Marilândia', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (48, 'Mimoso do Sul', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (49, 'Montanha', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (50, 'Mucurici', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (51, 'Muniz Freire', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (52, 'Muqui', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (53, 'Nova Venécia', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (54, 'Pancas', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (55, 'Pedro Canário', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (56, 'Pinheiros', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (57, 'Piúma', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (58, 'Ponto Belo', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (59, 'Presidente Kennedy', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (60, 'Rio Bananal', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (61, 'Rio Novo do Sul', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (62, 'Santa Leopoldina', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (63, 'Santa Maria de Jetibá', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (64, 'Santa Teresa', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (65, 'São Domingos do Norte', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (66, 'São Gabriel da Palha', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (67, 'São José do Calçado', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (68, 'São Mateus', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (69, 'São Roque do Canaã', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (70, 'Serra', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (71, 'Sooretama', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (72, 'Vargem Alta', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (73, 'Venda Nova do Imigrante', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (74, 'Viana', 8);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (75, 'Vila Pavão', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (76, 'Vila Valério', 8);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (77, 'Vila Velha', 8);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (78, 'Vitória', 8); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (79, 'Acrelândia', 1);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (80, 'Assis Brasil', 1);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (81, 'Brasiléia', 1);   
INSERT INTO CIDADE (id, nome, estado_id) VALUES (82, 'Bujari', 1);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (83, 'Capixaba', 1);    
INSERT INTO CIDADE (id, nome, estado_id) VALUES (84, 'Cruzeiro do Sul', 1); 
INSERT INTO CIDADE (id, nome, estado_id) VALUES (85, 'Epitaciolândia', 1);  
INSERT INTO CIDADE (id, nome, estado_id) VALUES (86, 'Feijó', 1);